// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'market_controller.dart';

// **************************************************************************
// ShelfRouterGenerator
// **************************************************************************

Router _$MarketControllerRouter(MarketController service) {
  final router = Router();
  router.add(
    'GET',
    r'/api/market/categories/main',
    service.getMainCategories,
  );
  router.add(
    'GET',
    r'/api/market/categories',
    service.getAllCategories,
  );
  router.add(
    'GET',
    r'/api/market/categories/<id>',
    service.getCategoryById,
  );
  router.add(
    'GET',
    r'/api/market/aircraft',
    service.getProducts,
  );
  router.add(
    'GET',
    r'/api/market/aircraft/<id>',
    service.getProductById,
  );
  router.add(
    'GET',
    r'/api/market/aircraft/<id>/price-history',
    service.getPriceHistory,
  );
  router.add(
    'GET',
    r'/api/market/parts/<id>/price-history',
    service.getPartPriceHistory,
  );
  router.add(
    'POST',
    r'/api/market/aircraft',
    service.createAircraft,
  );
  router.add(
    'POST',
    r'/api/market/aircraft/<id>/favorite',
    service.addToFavorites,
  );
  router.add(
    'DELETE',
    r'/api/market/aircraft/<id>/favorite',
    service.removeFromFavorites,
  );
  router.add(
    'GET',
    r'/api/market/favorites',
    service.getFavorites,
  );
  router.add(
    'PUT',
    r'/api/market/aircraft/<id>',
    service.updateProduct,
  );
  router.add(
    'POST',
    r'/api/market/aircraft/<id>/publish',
    service.publishProduct,
  );
  router.add(
    'POST',
    r'/api/market/aircraft/<id>/unpublish',
    service.unpublishProduct,
  );
  router.add(
    'POST',
    r'/api/market/aircraft/<id>/deactivate',
    service.deactivateAircraft,
  );
  router.add(
    'POST',
    r'/api/market/aircraft/<id>/activate',
    service.activateAircraft,
  );
  router.add(
    'DELETE',
    r'/api/market/aircraft/<id>',
    service.deleteProduct,
  );
  router.add(
    'POST',
    r'/api/market/products/<id>/main-image',
    service.uploadMainImage,
  );
  router.add(
    'POST',
    r'/api/market/products/<id>/additional-images',
    service.uploadAdditionalImages,
  );
  router.add(
    'GET',
    r'/api/market/parts/main-categories',
    service.getPartsMainCategories,
  );
  router.add(
    'GET',
    r'/api/market/parts/subcategories',
    service.getPartsSubcategories,
  );
  router.add(
    'GET',
    r'/api/market/parts/manufacturers',
    service.getPartsManufacturers,
  );
  router.add(
    'GET',
    r'/api/market/parts',
    service.getParts,
  );
  router.add(
    'GET',
    r'/api/market/parts/<id>',
    service.getPartById,
  );
  router.add(
    'POST',
    r'/api/market/parts',
    service.createPart,
  );
  router.add(
    'PUT',
    r'/api/market/parts/<id>',
    service.updatePart,
  );
  router.add(
    'POST',
    r'/api/market/parts/<id>/publish',
    service.publishPart,
  );
  router.add(
    'POST',
    r'/api/market/parts/<id>/unpublish',
    service.unpublishPart,
  );
  router.add(
    'POST',
    r'/api/market/parts/<id>/deactivate',
    service.deactivatePart,
  );
  router.add(
    'POST',
    r'/api/market/parts/<id>/activate',
    service.activatePart,
  );
  router.add(
    'DELETE',
    r'/api/market/parts/<id>',
    service.deletePart,
  );
  router.add(
    'POST',
    r'/api/market/parts/<id>/favorite',
    service.addPartToFavorites,
  );
  router.add(
    'DELETE',
    r'/api/market/parts/<id>/favorite',
    service.removePartFromFavorites,
  );
  router.add(
    'GET',
    r'/api/market/parts/favorites',
    service.getFavoriteParts,
  );
  return router;
}
