openapi: 3.0.0
info:
  title: Api
  version: 0.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /learning/video_for_students:
    get:
      tags:
        - VideoForStudentsController
      summary: Получение всех видео для студентов
      description: Получение всех обучающих видео для студентов
      operationId: getVideoForStudents
      responses:
        200:
          description: "Operation completed!"
  /learning/video_for_students/<id>:
    get:
      tags:
        - VideoForStudentsController
      summary: Получение конкретного видео для студентов
      description: Получение конкретного обучающих видео для студентов
      operationId: getVideoById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /user:
    post:
      tags:
        - ProfileController
      summary: Создание пользователя
      description: Возвращает в ответе данные пользователя
      operationId: createUser
      responses:
        200:
          description: "Operation completed!"
  /profiles:
    get:
      tags:
        - ProfileController
      summary: Получение профилей пользователей
      description: Получение всех профилей пользователей
      operationId: getUsers
      responses:
        200:
          description: "Operation completed!"
  /user/<userId>:
    delete:
      tags:
        - ProfileController
      summary: Удаление пользователя
      description: Удаление пользователя по userId
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/main_categories:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение основных категорий
      description: Получение всех основных категорий в Hand Book
      operationId: fetchHandBookCategoties
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/preflight_inspection_categories:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение категорий для Предполётных процедур
      description: Hand Book. Получение категорий для Предполётных процедур
      operationId: fetchPreflightInspectionCaegories
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/preflight_inspection_categories/check_list:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение чек листа в Preflight inspetion
      description: Hand Book. Получение чек листа для Предполётных процедур
      operationId: fetchPreflightInspectionCheckList
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/preflight_inspection_categories/check_list/<id>:
    get:
      tags:
        - HandBookController
      summary: Получение конкретной проверки из чеклиста
      description: Получение конкретной проверки из чеклиста по id
      operationId: fetchPreflightInspectionCheckListById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
components: { }
tags:
  - name: VideoForStudentsController
  - name: ProfileController
  - name: HandBookController