openapi: 3.0.0
info:
  title: Api
  version: 0.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /auth/sms:
    post:
      tags:
        - AuthController
      summary: Отправление sms
      description: Отправление sms пользователю на телефон
      operationId: sendSms
      responses:
        200:
          description: "Operation completed!"
  /auth/login:
    post:
      tags:
        - AuthController
      summary: Логин
      description: Логин по телефону и смс
      operationId: login
      responses:
        200:
          description: "Operation completed!"
  /auth/refresh:
    post:
      tags:
        - AuthController
      summary: refreshToken
      operationId: refreshToken
      responses:
        200:
          description: "Operation completed!"
  /learning/video_for_students:
    get:
      tags:
        - VideoForStudentsController
      summary: Получение всех видео для студентов
      description: Получение всех обучающих видео для студентов
      operationId: getVideoForStudents
      responses:
        200:
          description: "Operation completed!"
  /learning/video_for_students/<id>:
    get:
      tags:
        - VideoForStudentsController
      summary: Получение конкретного видео для студентов
      description: Получение конкретного обучающих видео для студентов
      operationId: getVideoById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /learning/ros_avia_test/type_sertificates:
    get:
      tags:
        - RosAviaTestController
      summary: РосАвиаТест. Получение типов свидетельств
      description: Получение всех Получение типов свидетельств в РосАвиаТест
      operationId: fetchTypeSertificates
      responses:
        200:
          description: "Operation completed!"
  /learning/ros_avia_test/type_correct_answers:
    get:
      tags:
        - RosAviaTestController
      summary: РосАвиаТест. Получение типов корректности ответа
      description: Получение всех Получение типов корректности ответа
      operationId: fetchTypeCorrectAnswer
      responses:
        200:
          description: "Operation completed!"
  /learning/ros_avia_test/categories/<typeCertificateId>:
    get:
      tags:
        - RosAviaTestController
      summary: РосАвиаТест. Получение категорий
      description: РосАвиаТест. Получение категорий
      operationId: fetchRosAviaTestCategories
      parameters:
        - name: typeCertificateId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /learning/ros_avia_test/<typeCertificateId>:
    get:
      tags:
        - RosAviaTestController
      summary: РосАвиаТест. Получение категорий с вопросами отфильтрованным по типу сертификата
      description: РосАвиаТест. Получение категорий с вопросами отфильтрованным по типу сертификата
      operationId: fetchRosAviaTestCategoryWithQuestions
      parameters:
        - name: typeCertificateId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /learning/ros_avia_test/questions/<typeCertificateId>:
    get:
      tags:
        - RosAviaTestController
      summary: РосАвиаТест. Получение всех вопросов по выбранному сертификату и темам
      description: РосАвиаТест. Получение всех вопросов по выбранному сертификату и темам
      operationId: fetchQuestionsWithAnswersByCategoryAndTypeCertificate
      parameters:
        - name: typeCertificateId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/main_categories:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение основных категорий
      description: Получение всех основных категорий в Hand Book
      operationId: fetchHandBookCategoties
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/preflight_inspection_categories:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение категорий для Предполётных процедур
      description: Hand Book. Получение категорий для Предполётных процедур
      operationId: fetchPreflightInspectionCaegories
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/preflight_inspection_categories/check_list:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение чек листа в Preflight inspetion
      description: Hand Book. Получение чек листа для Предполётных процедур
      operationId: fetchPreflightInspectionCheckList
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/preflight_inspection_categories/check_list/<id>:
    get:
      tags:
        - HandBookController
      summary: Получение конкретной проверки из чеклиста
      description: Получение конкретной проверки из чеклиста по id
      operationId: fetchPreflightInspectionCheckListById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/normal_categories:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение категорий для Нормальных процедур
      description: Hand Book. Получение категорий для Нормальных процедур
      operationId: fetchNormalCategories
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/normal_categories/check_list:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение чек листа в Normal
      description: Hand Book. Получение чек листа для Предполётных процедур
      operationId: fetchNormalCheckList
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/normal_categories/check_list/<id>:
    get:
      tags:
        - HandBookController
      summary: Получение конкретной проверки из чеклиста Normal
      description: Получение конкретной проверки из чеклиста Normal по id
      operationId: fetchNormalCheckListById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /learning/hand_book/emergency_categories:
    get:
      tags:
        - HandBookController
      summary: Hand Book. Получение категорий для Аварийных процедур
      description: Hand Book. Получение категорий для Аварийных процедур
      operationId: fetchEmergencyCategories
      responses:
        200:
          description: "Operation completed!"
  /stories:
    get:
      tags:
        - StoriesController
      summary: Получение всех видео сториков
      description: Получение всех видео сториков
      operationId: getStories
      responses:
        200:
          description: "Operation completed!"
  /stories/<id>:
    get:
      tags:
        - StoriesController
      summary: Получение конкретного сторика
      description: Получение конкретного сторика
      operationId: getStory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /category_news:
    get:
      tags:
        - NewsController
      summary: Получение всех категорий для новостей
      description: Получение всех категорий для новостей
      operationId: getCategoryNews
      responses:
        200:
          description: "Operation completed!"
  /news:
    get:
      tags:
        - NewsController
      summary: Получение всех видео сториков
      description: Получение всех видео сториков
      operationId: getnews
      responses:
        200:
          description: "Operation completed!"
  /news/<id>:
    get:
      tags:
        - NewsController
      summary: Получение конкретной новости
      description: Получение конкретной новости
      operationId: getNewsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /news/category/<id>:
    get:
      tags:
        - NewsController
      summary: Получение новостей по конкретной категории
      description: Получение новостей по конкретной категории
      operationId: getNewsByCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /user:
    post:
      tags:
        - ProfileController
      summary: Создание пользователя
      description: Возвращает в ответе данные пользователя
      operationId: createUser
      responses:
        200:
          description: "Operation completed!"
  /profiles:
    get:
      tags:
        - ProfileController
      summary: Получение профилей пользователей
      description: Получение всех профилей пользователей
      operationId: getUsers
      responses:
        200:
          description: "Operation completed!"
  /profile:
    post:
      tags:
        - ProfileController
      summary: Получение профиля
      description: Получение всех профиля пользователя
      operationId: getProfile
      responses:
        200:
          description: "Operation completed!"
  /payments/create:
    post:
      tags:
        - PaymentController
      summary: Создание платежа
      description: Создает платеж в ЮKassa и возвращает paymentUrl
      operationId: createPayment
      responses:
        200:
          description: "Operation completed!"
  /payments/<paymentId>/status:
    get:
      tags:
        - PaymentController
      summary: Получение статуса платежа
      description: Проверяет статус платежа по ID
      operationId: getPaymentStatus
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
  /payments/return:
    get:
      tags:
        - PaymentController
      summary: Обработка возврата после успешной оплаты
      description: ЮKassa редиректит пользователя на этот URL после успешной оплаты
      operationId: paymentReturn
      responses:
        200:
          description: "Operation completed!"
  /payments/cancel:
    get:
      tags:
        - PaymentController
      summary: Обработка отмены платежа
      description: ЮKassa редиректит пользователя на этот URL при отмене платежа
      operationId: paymentCancel
      responses:
        200:
          description: "Operation completed!"
  /payments/webhook:
    post:
      tags:
        - PaymentController
      summary: Webhook от ЮKassa
      description: Получает уведомления о статусе платежа от ЮKassa
      operationId: webhook
      responses:
        200:
          description: "Operation completed!"
  /subscriptions/status:
    get:
      tags:
        - SubscriptionController
      summary: Получение статуса подписки текущего пользователя
      description: Проверяет наличие активной подписки у пользователя
      operationId: getSubscriptionStatus
      responses:
        200:
          description: "Operation completed!"
  /subscriptions/active:
    get:
      tags:
        - SubscriptionController
      summary: Получение всех активных подписок пользователя
      description: "Возвращает список всех активных подписок пользователя.\nИспользует токен авторизации для определения пользователя.\nВозвращает 404, если активных подписок нет."
      operationId: getActiveSubscription
      responses:
        200:
          description: "Operation completed!"
  /subscriptions/history:
    get:
      tags:
        - SubscriptionController
      summary: Получение всех подписок пользователя
      description: Возвращает историю всех подписок пользователя
      operationId: getSubscriptionHistory
      responses:
        200:
          description: "Operation completed!"
components: { }
tags:
  - name: AuthController
  - name: VideoForStudentsController
  - name: RosAviaTestController
  - name: HandBookController
  - name: StoriesController
  - name: NewsController
  - name: ProfileController
  - name: PaymentController
  - name: SubscriptionController